"""empty message

Revision ID: 51d854bfeb4b
Revises: f49e5a3a7428
Create Date: 2025-09-06 21:56:23.677423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d854bfeb4b'
down_revision = 'f49e5a3a7428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
