"""empty message

Revision ID: 6daee1877dbd
Revises: e271467a4ac5
Create Date: 2025-09-11 01:42:10.407307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6daee1877dbd'
down_revision = 'e271467a4ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=200), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
