"""empty message

Revision ID: f49e5a3a7428
Revises: f8aff023447b
Create Date: 2025-09-06 18:49:43.807756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49e5a3a7428'
down_revision = 'f8aff023447b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_comment_story_chapter_created', ['story_id', 'chapter_id', 'created_at'], unique=False)
        batch_op.create_foreign_key(None, 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_comment_story_chapter_created')
        batch_op.drop_column('chapter_id')

    # ### end Alembic commands ###
