"""empty message

Revision ID: f8aff023447b
Revises: 1e155998afce
Create Date: 2025-09-04 01:59:18.492609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8aff023447b'
down_revision = '1e155998afce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('story_tag',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'tag_id')
    )

    # 🔧 Evita duplicar los CHECK constraints si ya existen
    op.execute("ALTER TABLE chapter DROP CONSTRAINT IF EXISTS chapter_status")
    op.execute("ALTER TABLE story DROP CONSTRAINT IF EXISTS story_status")

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'DELETED', name='chapter_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'DELETED', name='story_status', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        # 🔧 Suelta el CHECK antes de revertir el tipo
        batch_op.drop_constraint('story_status', type_='check')
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'DELETED', name='story_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        # 🔧 Suelta el CHECK antes de revertir el tipo
        batch_op.drop_constraint('chapter_status', type_='check')
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'DELETED', name='chapter_status', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))

    op.drop_table('story_tag')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###